#!/usr/bin/python

'''Raspberry Pi relay test script 3.
Find more information on this script at
http://youtu.be/oaf_zQcrg7g
Original script: http://lpaste.net/104491'''

import RPi.GPIO as GPIO
import time
import argparse

parser = argparse.ArgumentParser(description='Loops through relays and '
                                             'toggles them in a pattern')
parser.add_argument('-s', metavar='SleepTime', default='0.2',
                    help='The time to sleep between relay toggles')
args = parser.parse_args()

GPIO.setmode(GPIO.BCM)

# init list with gpio numbers
gpioList = [2, 3, 4, 17, 27, 22, 10, 9]

# loop through pins and set mode and state to 'low'
for i in gpioList:
    GPIO.setup(i, GPIO.OUT)
    GPIO.output(i, GPIO.HIGH)

# main loop
try:
    while True:
        for i in gpioList:
            GPIO.output(i, GPIO.HIGH)
            time.sleep(SleepTime);

        #gpioList.reverse()

        for i in gpioList:
            GPIO.output(i, GPIO.LOW)
            time.sleep(SleepTime);

        gpioList.reverse()

# End program cleanly with keyboard
except KeyboardInterrupt:
    print "  Quit"

    # Reset GPIO settings
    GPIO.cleanup()
