#!/usr/bin/python

'''Raspberry Pi relay test script 3.
Find more information on this script at
http://youtu.be/oaf_zQcrg7g
Original script: http://lpaste.net/104491'''

import RPi.GPIO as GPIO
import time
import argparse

parser = argparse.ArgumentParser(description='Loops through relays and '
                                             'toggles them in a pattern')
parser.add_argument('--sleeptime', '-s', default='0.2', type=float,
                    help='time to sleep between relay toggles')
args = parser.parse_args()

GPIO.setmode(GPIO.BCM)

# init list with gpio numbers
gpioList = [2, 3, 4, 17, 27, 22, 10, 9]

# loop through pins and set mode and state to 'low'
for i in gpioList:
    GPIO.setup(i, GPIO.OUT)
    GPIO.output(i, GPIO.HIGH)

def gpioSet(pin,state):
    GPIO.output(i, state)
    time.sleep(args.sleeptime);

def gpioHigh(pin):
    gpioSet(pin, GPIO.HIGH)

def gpioLow(pin):
    gpioSet(pin, GPIO.LOW)

# main loop
try:
    while True:
        for i in gpioList:
            gpioHigh(i)

        #gpioList.reverse()

        for i in gpioList:
            gpioLow(i)

        gpioList.reverse()

# End program cleanly with keyboard
except KeyboardInterrupt:
    print "  Keyboard interrupt, quitting."

finally:
    # Reset GPIO settings
    GPIO.cleanup()
